##架构设计：
###配置文件中，第一层是数据模块，第二层是数据组件，ModuleConfiguration
###一个模块对应对个组件(ModuleDef)，一个组件对应一个容器(ContainerDefinition)，意思就是一个模块对应多个容器
###第一步：加载配置文件
###第二步：初始化容器，实现依赖注入（比如postgresql实例，对应的配置）
core:
  which: default
  default:
    metaDataStorage: mysql
    deviceDataStorage: postgresql
    ## 物模型、传输协议（gateway）插件、消息协议插件
device:
  which: default
  default:
  ##
network:
  which: mqtt,http
  mqtt:
    host: localhost
    port: 1883
    userName: admin
    password: public
    clientId: test-clientId
  http:
    port: 18080
    workThreads: 10
storage:
  which: postgresql,elasticsearch7,mysql
  postgresql:
    url: r2dbc:postgresql://localhost:5432/giot
    username: postgres
    password: giot
  elasticsearch:
    url: 127.0.0.1:9200
    username: elasticsearch
    password: giot
  mysql:
    properties:
      jdbcUrl: jdbc:mysql://localhost:3306/giot
      dataSource.user: root
      dataSource.password: 123456
      dataSource.cachePrepStmts: true
      dataSource.prepStmtCacheSize: 250
      dataSource.prepStmtCacheSqlLimit: 2048
      dataSource.useServerPrepStmts: true
  elasticsearch7:
    url: xxx